---
- name: download traefik helm chart
  get_url:
      url: https://kubernetes-charts.storage.googleapis.com/traefik-{{ traefik_version }}.tgz
      dest: /var/lib/rancher/k3s/server/static/charts
      owner: root
      group: root
      mode: 755

- name: download redis helm chart
  get_url:
      url: https://kubernetes-charts.storage.googleapis.com/redis-ha-{{ redis_ha_version }}.tgz
      dest: /var/lib/rancher/k3s/server/static/charts
      owner: root
      group: root
      mode: 755

- name: download opa helm chart
  get_url:
      url: https://kubernetes-charts.storage.googleapis.com/opa-{{ opa_version }}.tgz
      dest: /var/lib/rancher/k3s/server/static/charts
      owner: root
      group: root
      mode: 755

- name: Restart k3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Create helmchart manifests
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0777
  with_items:
    - {src: 'helm-dapr.j2', dest: '/var/lib/rancher/k3s/server/manifests/helm-dapr.yaml'}
    - {src: 'helm-gatekeeper.j2', dest: '/var/lib/rancher/k3s/server/manifests/helm-gatekeeper.yaml'}
    - {src: 'helm-redis-ha.j2', dest: '/var/lib/rancher/k3s/server/manifests/helm-redis-ha.yaml'}
    - {src: 'helm-traefik.j2', dest: '/var/lib/rancher/k3s/server/manifests/helm-traefik.yaml'}

- name: Copy manifests
  copy:
    src: "{{ playbook_dir }}/../manifests/"
    dest: "/var/lib/rancher/k3s/server/manifests"
    owner: root
    group: root
    mode: 0644
