---
- name: download traefik helm chart
  get_url:
      url: https://kubernetes-charts.storage.googleapis.com/traefik-1.86.0.tgz
      dest: /var/lib/rancher/k3s/server/static/charts
      owner: root
      group: root
      mode: 755

- name: Restart k3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Copy helmchart manifests
  copy:
    src: "{{ playbook_dir }}/../helm/"
    dest: "/var/lib/rancher/k3s/server/manifests"
    owner: root
    group: root
    mode: 0644

- name: Copy manifests
  copy:
    src: "{{ playbook_dir }}/../manifests/"
    dest: "/var/lib/rancher/k3s/server/manifests"
    owner: root
    group: root
    mode: 0644
