apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
  name: hello-world
  namespace: openfaas-fn
spec:
  image: pietervicloudcom/hello-world-armhf:node-6.9.1-alpine-armhf
  name: hello-world
  labels:
    com.openfaas.scale.min: "2"
    com.openfaas.scale.max: "10"