---

- name: Disable k3s service
  systemd:
    name: k3s
    enabled: no

- name: Reboot
  reboot:

- name: Remove rancher lib folder
  file:
    path: /var/lib/rancher/k3s
    state: absent

- name: Remove rancher etc folder
  file:
    path: /etc/rancher/k3s
    state: absent

- name: Remove k3s file
  file:
    path: /usr/local/bin/k3s
    state: absent

- name: Remove kubectl symlink
  file:
    path: /usr/local/bin/kubectl
    state: absent

- name: Remove crictl symlink
  file:
    path: /usr/local/bin/crictl
    state: absent



