---
- name: install aptitude
  apt:
    name: aptitude 
    state: present
    upgrade: yes

- name: update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day
  register: upgradeoccured

- name: reboot
  reboot:
  when: upgradeoccured

