apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki-stack
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/loki-stack-0.16.2.tgz
  targetNamespace: monitoring
  valuesContent: |-
    loki:
    enabled: true

    promtail:
      enabled: true

    grafana:
      enabled: false

    prometheus:
      enabled: false

      