apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki-stack
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/loki-stack-0.16.0.tgz
  targetNamespace: monitoring
  valuesContent: |-
    loki:
    enabled: true

    promtail:
      enabled: true

    grafana:
      enabled: false
      sidecar:
        datasources:
          enabled: true
      image:
        tag: 6.3.0-beta2

    prometheus:
      enabled: false
      server:
        fullnameOverride: prometheus-server

      