apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-1.64.0.tgz
  set:
    kubernetes.ingressEndpoint.useDefaultPublishedService: "true" 
    rbac.enabled: "true" 
    ssl.enabled: "true"
    dashboard.enabled: "true"
    dashboard.domain: "traefik.k3s.local"
    metrics.prometheus.enabled: "true"