---

- name: Disable k3s-node service
  systemd:
    name: k3s-node
    enabled: no

- name: Reboot
  reboot:

- name: Remove rancher folder
  file:
    path: /var/lib/rancher/
    state: absent

- name: Remove k3s file
  file:
    path: /usr/local/bin/k3s
    state: absent



